baseURL = 'https://countneuroman.github.io/'
languageCode = 'ru-RU'
title = 'Блог Вадима Алексеева'
theme='hugo-flex'
googleAnalytics='G-39RJXVCB0M'
publishDir = 'docs'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle"
	useCDN=true
	mathjax = false
	katex = false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/countneuroman/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/CountNeuroman/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/countneuroman/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

menu:
  nav:
    - name: About
      url: about.md
      weight: 1
    - name: Posts
      url: posts/
      weight: 2