baseURL = 'https://countneuroman.github.io/'
languageCode = 'ru-RU'
title = 'CountNeuroman блог'
theme='hugo-flex'
googleAnalytics='G-39RJXVCB0M'
publishDir = 'docs'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/countneuroman/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/CountNeuroman/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/countneuroman/"

[params]
summaries = true
footer = '<a href="https://github.com/countneuroman"><svg style="width: 5rem; height: 5rem; fill: white"><title>GitHub</title><use xlink:href="/all.svg#github"></use></svg></a> <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">CC BY-NC-SA 4.0</a>'

[[menu.nav]]
name = "About"
url = "about/"
weight = 1

[[menu.nav]]
name = "Posts"
url = "posts/"
weight = 2