baseURL = 'https://countneuroman.github.io/'
languageCode = 'ru-RU'
title = 'Блог Вадима Алексеева'
theme='archie'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle"
	useCDN=true
	mathjax = true
	katex = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/countneuroman/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/CountNeuroman/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/countneuroman/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3